### ISSUE TITLE
ch 18 Allocator init crashes with latest ash

### ISSUE THREAD

**Issue by xla** [hoj-senna/ashen-aetna#2]
Hej, first of thanks for this amazing and in-depth tutorial (might be even beyond that). I implemented it while following along, with one difference, I'm using `0.31` of ash. Which produces the following panic in chapter 18:

```
thread 'main' panicked at 'attempted to zero-initialize type `ash::Device`, which is invalid', /home/xla/.rustup/toolchains/nightly-2020-12-13-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/mem/mod.rs:623:9
```

It stems from gwihlidal/vk-mem-rs#42 and should be fixed once `0.2.3` has landed.

Including my `Cargo.toml`:

``` toml
[package]
name              = "vulkanrenderer"
version           = "0.1.0"
authors           = ["Alexander Simmerl <a.simmerl@gmail.com>"]
edition           = "2018"

[dependencies]
ash               = "0.31"
vk-mem            = "0.2"
vk-shader-macros  = "0.2"
winit             = "0.24"

```
